### PR TITLE
Merge small macro changes in various files

### PR DESCRIPTION
**Pull request by hochleitner**
Let's keep book in favor of scrbook for now. Yet while trying this out I came across a few TeX commands in various files such as \bf, \rm, \it and the like. I replaced those with LaTeX equivalents. It shouldn't have any visible effects, yet it makes the document more compatible to other classes and styles.

### CODE REVIEW

**Comment by hochleitner** [comment]
@WilhelmBurger please have a look at the changes and merge if there are no issues in your opinion.

**Comment by WilhelmBurger** [comment]
Thanks!

**Comment by hochleitner** [comment]
Wait, you closed this PR *without* merging the commits into `master`. Was this done on purpose?

**Comment by WilhelmBurger** [comment]
Oha! Should be done now, sorry.

**Pull request merged**
