### PR TITLE
Include DOIs in references

### LINKED ISSUE #146: Include DOI in references
People in our department, notably @schedldave, requested that we include DOIs in the references. They are standardized and way shorter than URLs (especially long and ugly ones to sites like Research Gate), and Biblatex converts them to a clickable URL nicely.

I do support this because it makes digitally reviewing a thesis easier. One does not need to search for a referenced paper but can access it through the DOI. Yet it does not blow up entries as any arbitrary URL could do.

The only issue is that most exporter citations (from ACM, IEEE and the like) tend to have a `doi` and an `url` field set (which contains the DOI URL). This creates reference entries with the DOI appearing twice. To counter this, I suggest adding a rule to `hgbbib.sty` that goes through the items and clears the `url` entry when `doi` is present. Something like this (inspired from [here](https://tex.stackexchange.com/questions/381491/biblatex-numeric-comp-suppress-doi-and-url-for-journals-unless-the-article)) should do the trick:

```latex
\AtEveryBibitem{
    \iffieldundef{doi}{}{\clearfield{url}}
}
```

If necessary, we can limit this to specific bib types, but I can't think of anything where a DOI and an URL are both required.

### PR DESCRIPTION
**Pull request by hochleitner**
I've reworked `HgbThesisTutorial` to include DOIs in references. The following things were changed:

- `hgbbib.sty` now enables DOIs for all bibliography items.
- If a `doi` field is present, the `url` field is cleared. This is because most citation exports from sites like ACM or IEEE have a `doi` entry and an `url` entry with the DOI URL set. This would result in both things being displayed, which is both redundant and ugly.
- Added a DOI to every existing literature item in `references.bib` where available.
- Updated instructions `literatur.tex`: DOIs are now recommended; examples include the DOI.
- I also switched the arXiv entry to the DOI instead of the URL since arXiv does have DOIs enabled for all their submissions.
- Files in `dev/latex` have been updated as well; no full build yet (please test/review first).

@imagingbook, @schedldave - please build `HgbThesisTutorial` and look at chapter 6 and the references in the back. Please correct or add anything that comes to mind.
As @imagingbook suggested, not all items have DOIs. I added them where I could find some, but there are enough examples without one. I don't think that any of the books we list have a DOI. I don't know if it would even make sense to add one.

This PR closes #146.

### CODE REVIEW

**Comment by imagingbook** [comment]
Everything looks good. I revised `literatur.tex` once again, added a few more DOIs and updated some formulations. Also felt the strong need to reformat the file ...
@hochleitner Don't you think a new release is overdue?

**Comment by hochleitner** [comment]
Yes, a release is overdue; there are just a few more things I'd like to get done before releasing it. I've created a milestone (https://github.com/Digital-Media/HagenbergThesis/milestone/2) with the things I'd like to include until the end of February 2023. This would mean the new release is in time for the upcoming master's theses.

I'm also keeping a backlog that helps me track the things that need to be done:  https://github.com/orgs/Digital-Media/projects/1

Concerning reformatting: how do you feel about dropping line breaks at 80 characters and just having full line widths? Shouldn't any decent editor be capable of adding soft wraps at any desired number anyway?

**Comment by imagingbook** [comment]
> Yes, a release is overdue..
Very well, let's wait for milestone completion then.

> I'm also keeping a backlog..
Kudos, you are so well organized!

> Concerning reformatting..
Yes, a fixed line length would be good, makes everything more readable. I used 120 characters per line, since 80 looks awfully short on modern screens. And it is surprisingly hard to find a text editor that does automatic line wrapping (i.e., "reformat") properly. Had to revert to IntelliJ (with TeXiFy plugin) to fix that file, would welcome a better alternative ...

**Comment by imagingbook** [comment]
> Concerning reformatting ...
Hm, I am not a great friend of soft wraps, since the text appearance keeps changing with window size, which sometimes makes things hard to locate. Guess I prefer hard wraps (I used 120 char/line) in the last edit...

**Comment by hochleitner** [comment]
Alright, let's stay with this. Works for me.

Did you ever check if there's a usable LaTeX source linter that could help maintaining a consistent coding style/source formatting?

**Comment by imagingbook** [comment]
Thx. Yes I checked for such a tool some time ago but found none. This is why I started a project myself (which is on halt now)...

**Comment by hochleitner** [comment]
I wasn't thinking so much about a tool that checks for the validity of LaTeX markup, rather than something that beautifies the code, so that indentations, linebreaks and such things are consistent.

Maybe this could help? https://ctan.org/pkg/latexindent

**Comment by imagingbook** [comment]
Ah, OK (I'd still call it a tool). I tried `latexindent` but could not get it to run, although available as an executable in MikTeX. I have been using IntelliJ (with the TeXiFy plugin) recently for semi-manual formatting. Interestingly, this plugin too has an option to run `latexindent` but it also fails on all our files. 
I am not sure I want to invest much more time into this. What's your intention? Are you looking for something to run on a regular basis or only once?

**Comment by hochleitner** [comment]
I just think that some consistent formatting would be nice for our template documents. Do we indent the content of environments? Should we use a more visual indentation for tables (align the & characters) and other things.

If we found something that works, I'd run it on the files that were modified and then commit.

**Comment by imagingbook** [comment]
Yes, cleaner code would be nice. In the meantime I got `latexindent` running and did a few experiments. Some parts look OK but others are more of a mess than before. Everything is configurable, still playing (probably the worst-looking manual I have ever seen)...

**Pull request merged**
