### PR TITLE
Expand section on tables in `HgbThesisTutorial`

### LINKED ISSUE #138: Consider Booktabs for Tables
Stephan Dreiseitl suggested that we take a look at the [Booktabs](https://ctan.org/pkg/booktabs) package for typesetting the tables in the thesis tutorial document.

Here are some arguments why this might be a good idea: https://nhigham.com/2019/11/19/better-latex-tables-with-booktabs/

I'm not much of an expert in this matter, but these tables do have a more clean look, and it seems like publishers are using them.

In the course of this, it might also be a good idea to include multicolumn and multirow since these are used quite often.

### PR DESCRIPTION
**Pull request by hochleitner**
This PR has a few changes that all concern the tables section in `abbildungen.tex` of `HgbThesisTutorial`:

1. Switched the table layout to the `booktabs` package for all tables in the entire document. This reflects the changes suggested in #138.
2. Added more introductory text about tables and how the parameters in the `tabular` work.
3. Added information on modern tables that explains the reasoning behind `booktabs`.
4. Added a subsection about multipage tables using `longtable`, including an example.
5. Added a subsection about merging columns and rows, including an example.
6. Adapted `hgb.sty` with the required packages and added two entries to `references.sty`.

@imagingbook, please look and check if you agree with these suggestions. I did not include a full rebuild yet, but I changed all the files in the `HgbThesisTutorial` folder so you can build the example. `.sty` and `.bib` files in `dev/latex` are also updated so that a full build will place the changes accordingly.

The reasoning behind this was the suggestion by Stephan Dreiseitl about `booktabs` on the one hand. On the other hand, students struggle with typesetting tables quite a lot which is why explaining their workings a bit further makes sense.

This closes #138.

### CODE REVIEW

**Comment by imagingbook** [comment]
Very nice. However, there is a sentence I do not understand (in `abbildungen.tex`, line 568):
"Unterführungszeichen, wie etwa Anführungszeichen, werden nicht benutzt, um einen Wert zu wiederholen. Meist reicht eine leere Spalte völlig aus. Falls nicht, sollte der Wert wiederholt werden."
I have no clue what this means ...

**Comment by hochleitner** [comment]
This means, if you're repeating a value in the table you shouldn't do this:

| Item   | Color |
| ------ | ----- |
| Pencil | Red   |
| "      | Green |
| "      | Blue  |

Instead you should either repeat the value like this:

| Item   | Color |
| ------ | ----- |
| Pencil | Red   |
| Pencil | Green |
| Pencil | Blue  |

or just leave it blank:

| Item   | Color |
| ------ | ----- |
| Pencil | Red   |
|        | Green |
|        | Blue  |

" is an "Unterführungszeichen". Ditto mark in English. If that's too confusing, we can just leave it out.

**Comment by imagingbook** [comment]
> Unterführungszeichen

Never heard this term and I doubt that the majority of our readers did. I suggest to remove that sentence or give an example. But the whole section is already quite detailed ...

**Comment by hochleitner** [comment]
I removed the sentence completely. It's probably too specific and might even clash with DIN 5008 that explicitly allows ditto marks: https://www.sekada.de/din-5008/din-lexikon-a-z/artikel/din-5008-unterfuehrungszeichen-statt-wortwiederholung/

If you're happy with it, please merge the PR and maybe do a full rebuild, so we have a working main branch. I'll implement a few other changes soon, so I'll probably bother you again. 😬

**Comment by imagingbook** [comment]
> I removed the sentence completely. It's probably too specific and might even clash with DIN 5008 that explicitly allows ditto marks: https://www.sekada.de/din-5008/din-lexikon-a-z/artikel/din-5008-unterfuehrungszeichen-statt-wortwiederholung/
> 
> If you're happy with it, please merge the PR and maybe do a full rebuild, so we have a working main branch. I'll implement a few other changes soon, so I'll probably bother you again. 😬

Done. I also saw that there even is a special UTF character for ditto marks (I had no idea), so it is probably used here and there ...

**Pull request merged**
