### PR TITLE
Reformat source

### PR DESCRIPTION
**Pull request by imagingbook**
I reformatted all LaTeX source files in `HgbThesisTutorial` as discussed, back again to 80 chars/line (to ease life for split-screen users in Overleaf). This was done semi-automatically since none of the available tools works cleanly, i.e., they all make serious mistakes (particularly around comments and verbatim elements). Some obvious typos and obsolete comments were removed as well.

@hochleitner The document compiles properly but there may be subtle undetected errors. Pls. do a quick check if anything looks out of the normal.

### CODE REVIEW

**Review by hochleitner — APPROVED** [review]
I had a look all the files. Looks good to me, I added one commit with two or three things that looked weird after reformatting but nothing serious.

**Comment by imagingbook** [comment]
Thx. Found this recently, interesting perhaps for future use:
https://siefkenj.github.io/latex-parser-playground/   -- cool!
https://github.com/siefkenj/prettier-plugin-latex
https://github.com/siefkenj/unified-latex

**Comment by imagingbook** [comment]
@hochleitner Should we protect the main branch?

**Comment by hochleitner** [comment]
We can, but it would mean that every change would need to be made through a PR. 
While I think that this is definitely the responsible way to work it's also more cumbersome for us. There are only a few people with write access to this repo anyway.

**Pull request merged**
